services:
  app:
    build:
      context: .
    container_name: app
    restart: always
    profiles:
      - default
    ports:
      - '5000:5000'
    environment:
      DB_HOST: mariadb
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
    depends_on:
      - mariadb
  mariadb:
    container_name: db
    image: mariadb:latest
    restart: always
    profiles:
      - default
      - dev
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

  mariadb_test:
    container_name: db_test
    image: mariadb:latest
    restart: always
    profiles:
      - test
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    tmpfs:
      - /var/lib/mysql
volumes:
  mariadb_data:
